[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
version = "latest"
included-patches = "'Enable slide to seek'"
excluded-patches = "'Enable debugging' 'Theme'"
